services:
  web:
    build: .
    container_name: glpi_web
    ports:
      - "8081:80"
    volumes:
      - ./glpi:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: glpi_mysql
    environment:
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
      MYSQL_ROOT_PASSWORD: glpi
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:

